/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:3d51eb70-9a27-4dfb-80e6-2548a0ab83cc",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_rkvv2L5GT",
    "aws_user_pools_web_client_id": "3j72ojvpfb4olqmt94jghunkp7",
    "oauth": {}
};


export default awsmobile;
